language: node_js
node_js:
- 12.8.0
services:
- postgresql
before_script:
- cp config/config.json.travis config/config.json
- psql -c 'create database travis_ci_test;' -U postgres
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: TOFOqdLAAbK5xAr2E82DrHC3yYmlZtbQBjgUEF8Liv6rgG0eb4wAGJBXy3MgkmBsrjZOyKyAM/kMlrm0OS9IFkSoFWqFz2ECsOrnCsMCh3cSSVQ5qRaBt8Nf14aoPg82WZFBRdJI6UAFotVN4iunWtO2Z0Ovx7rY6wnywdznCkrUWZgBabPy8O9xZKtV+T7IYoAWHCwebsPLaTqRUzbcwDKMXTUq10lexpBTTiQk1BK1Q8R7KGP+mMQHpewTP2uSgpitjSq5k/E03dlNtU81Kg+LKcz73nTrlKDQbmjT0NiwbbprQOZCosQ0u3EXE9I8Sv7jS1wmIrFi7fo8Hl8JwQfJWtFcczvr9RpaOzpqCUHt/IE/Q4nFOoIYQdqACjng7oBkldTnqxiAdme67SYTybMiaeMfl80w0Hh+yawGTBXExzCYTczXx/Ba7q9EBrbPEVRBhHHsdQeRdOVhZFIi0uMcs2tX2xZrSr7ij/eR2OrkTet7ACJcOPFMZ49y8+5Ky/yr5qhcCQ9ExGO74kIqpzJRLCrWXArlGZ5xBeHiFFo/qctSpnvtxL3yTA81qrsUzvuDFcgxmwJ6mVYGJAu3r9+wqdcDXFWl3KYqetuKrY+7M9cbAvGOKCyZ0nJFOHyfp/BnUif5kYhNSeLhlbZaYUkizLW2OpmrSodBjylZKC8=
  app: floating-savannah-19561
